export const heroSlides=[
{key:"cloud",className:"h-cloud",eyebrow:"CLOUD & INFRASTRUCTURE",heading:"Modernize the foundation your business depends on.",lede:"Modernize infrastructure, cloud platforms and core technology foundations for resilience, performance and scale."},
{key:"cyber",className:"h-cyber",eyebrow:"CYBERSECURITY & RESILIENCE",heading:"Reduce technology risk. Improve readiness.",lede:"Build practical security and resilience across cloud, infrastructure, identity and critical operations."},
{key:"ai",className:"h-ai",eyebrow:"AI TRANSFORMATION",heading:"Move AI from experimentation to business execution.",lede:"Turn AI opportunities into secure, scalable workflows, automation and measurable business outcomes."}
];
export const partners=["AWS","Microsoft Azure","Google Cloud","Microsoft","Palo Alto Networks","Cisco","VMware","Dell","HPE","IBM","SAP","Oracle"];
export const navData=[
{label:"Services & Solutions",items:[
{t:"Cloud & Infrastructure Modernization",href:"/solutions/cloud-infrastructure"},{t:"Cybersecurity & Business Resilience",href:"/solutions/cybersecurity-resilience"},{t:"AI Transformation & Intelligent Automation",href:"/solutions/ai-automation"},{t:"IT Strategy & Digital Transformation Advisory",href:"/solutions/it-strategy"},{t:"Managed IT & Operations",href:"/solutions/managed-it"},{t:"Technology Talent & Professional Services",href:"/solutions/technology-talent"},{t:"AIDANT REVA™ Revenue Execution Suite",href:"/solutions/ai-automation/reva"}]},
{label:"Industries",items:[{t:"AI-First Product Companies",href:"/industries/ai-first"},{t:"Manufacturing",href:"/industries/manufacturing"},{t:"Healthcare",href:"/industries/healthcare"}]},
{label:"Resources",items:[{t:"Case Studies",href:"/resources/case-studies"},{t:"Trends & Insights",href:"/resources/insights"},{t:"Use Cases",href:"/resources/use-cases"},{t:"White Papers & Guides",href:"/resources/white-papers"}]},
{label:"About",href:"/about"},{label:"Contact",href:"/contact"}
];
export const beliefs=[{strong:"Business first.",rest:"Start with the problem, not the technology."},{strong:"Architecture that works.",rest:"Design for delivery, operation and change."},{strong:"Security by design.",rest:"Build resilience into every transformation."},{strong:"Outcomes over activity.",rest:"Make progress visible and measurable."}];
export const journeySteps=[{num:"01",title:"Stabilize",desc:"Create reliability, visibility and control."},{num:"02",title:"Modernize",desc:"Upgrade infrastructure, platforms and operating models."},{num:"03",title:"Secure",desc:"Reduce exposure and strengthen resilience."},{num:"04",title:"Automate",desc:"Remove repetitive work and improve workflows."},{num:"05",title:"Scale",desc:"Build technology foundations that support growth."},{num:"06",title:"Transform",desc:"Turn technology into a strategic advantage."}];
export const challengePills=["Legacy infrastructure","Cloud complexity","Cyber risk","AI readiness","Operational efficiency","Technology talent"];
export const solutions=[{icon:"cloud",title:"Cloud & Infrastructure",text:"Modernize cloud, data center and infrastructure foundations.",href:"/solutions/cloud-infrastructure"},{icon:"shield",title:"Cybersecurity & Resilience",text:"Strengthen security, governance and business resilience.",href:"/solutions/cybersecurity-resilience"},{icon:"ai",title:"AI & Intelligent Automation",text:"Move practical AI use cases from idea to production.",href:"/solutions/ai-automation"},{icon:"compass",title:"IT Strategy",text:"Turn business priorities into executable technology roadmaps.",href:"/solutions/it-strategy"},{icon:"monitor",title:"Managed IT & Operations",text:"Operate critical environments with confidence.",href:"/solutions/managed-it"},{icon:"people",title:"Technology Talent",text:"Add specialist capability where delivery needs it.",href:"/solutions/technology-talent"}];
export const industries=[{title:"AI-First Product Companies",text:"Reliable, secure and scalable foundations for AI-native products.",href:"/industries/ai-first"},{title:"Manufacturing",text:"Technology modernization and IT/OT resilience for complex operations.",href:"/industries/manufacturing"},{title:"Healthcare",text:"Dependable systems, protected data and resilient workflows.",href:"/industries/healthcare"}];
export const workSteps=[{num:"01",title:"Understand",desc:"Clarify the business outcome and current environment."},{num:"02",title:"Assess",desc:"Identify constraints, risks and opportunities."},{num:"03",title:"Architect",desc:"Design a practical target state and roadmap."},{num:"04",title:"Execute",desc:"Deliver in stages with visible progress."},{num:"05",title:"Improve",desc:"Operate, measure and continuously optimize."}];
export const caseStudies=["Engineering a Global Co-Location Data Center Architecture for a Leading Real Estate Group","Modernizing Mission-Critical IT Infrastructure for an Enterprise Environment","Building Resilient Cloud and Infrastructure Operations for a Growing Business"];
const cards=(items,text)=>items.map(title=>({title,text}));
export const sitePages={
"solution:cloud-infrastructure":{eyebrow:"SERVICES · CLOUD & INFRASTRUCTURE",title:"Modernize the foundation your business depends on.",lede:"Cloud and infrastructure modernization designed around resilience, performance, security and business outcomes.",flow:"Assess → Architect → Modernize → Operate",sections:[{title:"Where we focus",items:["Cloud strategy and migration","Data center and colocation architecture","Hybrid and multi-cloud foundations","Infrastructure modernization","Cloud cost optimization","Resilience and business continuity"]},{title:"Business outcomes",cards:cards(["Modernization","Resilience","Performance","Cost control","Scalability","Operational visibility"],"Practical foundations designed for the next stage of growth.")}],finalCta:{title:"Ready to modernize?",text:"Start with the environment, constraint or business outcome you need to improve.",label:"Talk to an Architect"}},
"solution:cybersecurity-resilience":{eyebrow:"SERVICES · CYBERSECURITY",title:"Reduce technology risk. Improve readiness.",lede:"Practical cybersecurity and resilience across identity, cloud, infrastructure and critical operations.",flow:"Discover → Prioritize → Protect → Respond → Improve",sections:[{title:"Capabilities",items:["Security assessments","Zero Trust and identity","Cloud security","Vulnerability management","Governance and risk","Business resilience"]},{title:"Focus areas",cards:cards(["Risk reduction","Readiness","Visibility","Identity","Resilience","Governance"],"Security designed to support business continuity and transformation.")}],finalCta:{title:"Strengthen your resilience",text:"Bring us the security or readiness challenge you need to solve.",label:"Discuss Security & Resilience"}},
"solution:ai-automation":{eyebrow:"SERVICES · AI TRANSFORMATION",title:"Move AI from experimentation to business execution.",lede:"Enterprise AI consulting and intelligent automation spanning readiness, architecture, use cases, agents and governance.",flow:"Discover → Prepare → Pilot → Production → Scale",sections:[{title:"AI transformation",items:["AI readiness and strategy","Enterprise AI architecture","Generative AI","AI agents and workflow automation","Data readiness","Responsible AI and governance"]},{title:"Practical use cases",cards:cards(["Knowledge workflows","Process automation","Decision support","Customer operations","Revenue operations","Enterprise productivity"],"Start with a high-value workflow and build toward repeatable AI capability.")}],finalCta:{title:"Find your highest-value AI opportunity",text:"Start with the workflow, data or business problem you want to improve.",label:"Discuss AI Transformation"}},
"solution:it-strategy":{eyebrow:"SERVICES · IT STRATEGY",title:"Turn technology priorities into an executable roadmap.",lede:"Architecture-led advisory connecting business priorities, technology decisions and delivery planning.",flow:"Align → Assess → Architect → Roadmap → Execute",sections:[{title:"Advisory focus",items:["Technology strategy","Enterprise architecture","Digital transformation roadmaps","Technology operating models","Investment prioritization","Transformation governance"]}],finalCta:{title:"Make the next technology decision clearer",text:"Talk through the decision, constraint or transformation you are planning.",label:"Talk to an Architect"}},
"solution:managed-it":{eyebrow:"SERVICES · MANAGED IT",title:"Operate critical technology with confidence.",lede:"Managed IT and operations support across infrastructure, endpoints, cloud operations, monitoring and lifecycle management.",flow:"Monitor → Manage → Resolve → Optimize",sections:[{title:"Operations",items:["Infrastructure operations","Cloud operations","Endpoint management","Monitoring and support","Lifecycle management","Operational improvement"]}],finalCta:{title:"Improve day-to-day technology operations",text:"Bring us the operational challenge you need to stabilize or improve.",label:"Discuss Managed IT"}},
"solution:technology-talent":{eyebrow:"SERVICES · TECHNOLOGY TALENT",title:"Add specialist capability where delivery needs it.",lede:"Technology talent and professional services across cloud, infrastructure, cybersecurity, AI, architecture and engineering.",flow:"Define → Match → Mobilize → Deliver",sections:[{title:"Specialist capability",items:["Cloud engineering","Infrastructure","Cybersecurity","AI and data","Architecture","Project delivery"]}],finalCta:{title:"Need specialist technology capability?",text:"Tell us the skills, delivery stage and outcome you need to support.",label:"Discuss Technology Talent"}},
"solution:reva":{eyebrow:"AIDANT REVA™ · REVENUE EXECUTION",title:"Turn operational data into predictable cash flow.",lede:"REVA™ connects fragmented operational data, billing, compliance, enterprise systems, receivables, collections and revenue intelligence into one connected revenue execution flow.",flow:"Extract → Structure → Bill → Comply → Sync → Track → Collect → Insight",sections:[{title:"Revenue execution flow",items:["REVA Extract™","REVA Structure™","REVA Bill™","REVA Comply™","REVA Sync™","REVA Track™","REVA Collect™","REVA Insight™"]}],finalCta:{title:"Explore revenue execution with REVA™",text:"Start with the revenue process, data flow or collections challenge you want to improve.",label:"Request a REVA™ Assessment"}},
"industry:ai-first":{eyebrow:"INDUSTRIES · AI-FIRST",title:"Build AI products on reliable foundations.",lede:"Cloud, cybersecurity, AI architecture and technology advisory for AI-first product companies.",sections:[{title:"Where we focus",items:["Cloud architecture","AI infrastructure","Security and resilience","Data foundations","Platform scalability","Technology strategy"]}],finalCta:{title:"Build for the next stage of scale",text:"Discuss the architecture, security or operating challenge in front of your product team.",label:"Discuss Your Industry Challenge"}},
"industry:manufacturing":{eyebrow:"INDUSTRIES · MANUFACTURING",title:"Modernize without losing operational continuity.",lede:"Cloud, cybersecurity, automation and technology modernization for complex manufacturing environments.",sections:[{title:"Where we focus",items:["IT/OT security","Infrastructure modernization","Cloud transformation","Resilience","Automation","Operational visibility"]}],finalCta:{title:"Modernize without disrupting production",text:"Bring your plant, infrastructure or resilience challenge to the conversation.",label:"Discuss Your Industry Challenge"}},
"industry:healthcare":{eyebrow:"INDUSTRIES · HEALTHCARE",title:"Keep critical systems running.",lede:"Dependable systems, protected data and technology that supports clinical and business workflows.",sections:[{title:"Where we focus",items:["Infrastructure modernization","Cybersecurity and resilience","Data and interoperability","Cloud transformation","AI and workflow automation","Business continuity"]}],finalCta:{title:"Have a critical technology challenge?",text:"Start with the system, workflow or resilience issue you need to improve.",label:"Discuss Your Industry Challenge"}},
"resource:case-studies":{eyebrow:"RESOURCES · CASE STUDIES",title:"Transformation in practice.",lede:"Complex technology problems require more than a list of services. Case studies show context, architecture, delivery and outcomes.",sections:[{title:"Selected engagements",cards:cards(caseStudies,"Challenge → Approach → Architecture → Delivery → Outcome")},{title:"Publication note",text:"Customer names, exact scope, dates, technologies, metrics and publication permissions are to be confirmed before publication."}],finalCta:{title:"Discuss a similar challenge",text:"Talk through your environment and the outcome you are trying to reach.",label:"Talk to an Architect"}},
"resource:insights":{eyebrow:"RESOURCES · TRENDS & INSIGHTS",title:"Practical perspectives for technology leaders.",lede:"Explore topics around modernization, resilience, AI adoption and technology operations.",sections:[{title:"Explore the topics",cards:cards(["Cloud modernization: where to start","Practical AI adoption roadmaps","Cloud cost optimization","Cyber resilience for critical systems","IT/OT security priorities","Preparing enterprise data for AI","Moving AI pilots to production","Revenue automation and cash-flow optimization"],"A practical perspective for leaders planning the next stage of technology change.")}],finalCta:{title:"Have a topic you want to explore?",text:"Start a conversation around your modernization or transformation challenge.",label:"Explore Insights"}},
"resource:use-cases":{eyebrow:"RESOURCES · USE CASES",title:"Technology use cases organized around business problems.",lede:"Find practical starting points for common modernization, resilience, AI and revenue-operations challenges.",sections:[{title:"Business problems",cards:["Cloud Cost Optimization","Data Center Exit","AI Readiness","AI Workflow Automation","Cyber Resilience","Manufacturing IT/OT Security","Billing Automation","Collections Automation"].map(title=>({title,text:"A practical starting point for assessing the problem, architecture and next action."}))}],finalCta:{title:"Find the right starting point",text:"Tell us the business problem and we can identify a practical next step.",label:"Talk to an Architect"}},
"resource:white-papers":{eyebrow:"RESOURCES · WHITE PAPERS & GUIDES",title:"Guides for the next technology decision.",lede:"High-intent educational resources for teams planning modernization, resilience, AI and revenue transformation.",sections:[{title:"Guides",cards:cards(["Enterprise Cloud Modernization Guide","Cyber Resilience Assessment Guide","AI Readiness Checklist","Manufacturing IT/OT Security Guide","Revenue Automation and Cash-Flow Optimization Guide","Enterprise AI Architecture Guide"],"Guide content and download details will be added when the final approved asset is available.")},{title:"Download workflow",text:"Final PDFs, authors, gated-form fields and download links are to be confirmed."}],finalCta:{title:"Need help before the guide is ready?",text:"Talk to an architect about your current technology challenge.",label:"Talk to an Architect"}},
about:{eyebrow:"ABOUT AIDANT",title:"Technology expertise focused on business outcomes.",lede:"Aidant is an IT services and consulting firm helping businesses make better technology decisions, execute transformation and operate critical environments with confidence.",sections:[{title:"What we believe",items:["Start with the business problem.","Keep architecture practical.","Make technology decisions measurable.","Build for reliability and security.","Deliver in stages.","Stay accountable after implementation."]},{title:"How we are different",text:"We bring architecture, engineering and operations together. Recommendations are designed with delivery and long-term operation in mind."},{title:"Leadership & credentials",text:"Leadership names, roles, biographies, credentials, photographs, years established, certifications, partner status, locations and awards are to be confirmed."}],finalCta:{title:"Talk to Aidant",text:"Bring us the technology problem, decision or transformation you are working through.",label:"Talk to Aidant"}},
contact:{eyebrow:"CONTACT AIDANT",title:"Have a technology challenge worth solving?",lede:"Tell us what you are trying to improve, what is getting in the way and where you need help.",sections:[{title:"What can we help with?",cards:cards(["Cloud and infrastructure","Cybersecurity and resilience","AI and automation","IT strategy","Managed IT","Technology talent","REVA™ revenue automation"],"Tell us what you are trying to improve and where the current environment is getting in the way.")},{title:"Start the conversation",text:"The final production form should collect Name, Business email, Company, Job title, Country/region, What are you looking to solve? and Preferred contact method. Official contact details and form destination are to be confirmed."}],finalCta:{title:"Let's start with the problem",text:"A practical next step starts with understanding your current environment and desired outcome.",label:"Start the Conversation"}}
};
